---
from: markdown+emoji
---
## Teaching

**Introduction into Python** (2024/25)

This course provides an introduction into Python for Bachelor and Master students at the University of Dortmund and introduces several tools to enable reproducible and reliable programming, including python packaging, data wrangling, data visualization, version control and collaborative programming with Git and GitHub. By the end of the course, students should be capable of working on a self-selected project using Python, developing their own Python package and acquiring independently new Python knowledge.
[course repository](https://github.com/florence-bockting/python-class-24/){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-sm}


**Seminar on multilevel models** (2023/24)

This seminar provides basic knowledge about linear and generalized linear multilevel models. Approaches from the frequentist and Bayesian paradigms are discussed. Course objectives include building a conceptual understanding of the various application areas, mathematical models, and the general analysis workflow of hierarchical modelling. Concerning the implementational aspects, we will use the programming language R (particularly the R-packages `lme4` and `brms`). <br>
[course website](https://buerkner-lab-teaching.github.io/MLM-seminar/){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-sm}

**Introduction into Python** (2023/24)

This course provides an introduction in Python and introduces several tools to enable reproducible and reliable programming, including version control with `git`, collaborative programming via `GitHub`, testing with `pytest`, and documentation with `Sphinx`. By the end of the course, students should be capable of working on a project using Python and independently acquiring new Python knowledge.  <br>


## Thesis supervision

*2024/25*

+ Analysis of different initialization approaches for hyperparameter optimization with mini-batch stochastic gradient descent: A simulation study | Bachelor Thesis | TU Dortmund 
+ Sensitivity Analysis and Performance Evaluation of Varying Upper Thresholds for Discrete Likelihoods Using the Softmax-Gumbel Trick | Master thesis | TU Dortmund university

*2021/22*

+ The influence of response scales on the knowledge gain of underlying cognitive mechanisms: The role of uncertainty and truth perception in the Truth Effect | 
Bachelor thesis | Marburg university
+ Empirical test of core assumptions of the Referential Theory: Influence of repetition on perceived coherence | Bachelor thesis | Marburg university
+ Identification and testing of relevant psychological factors on truth judgments and the truth effect according to the Referential Theory | Bachelor thesis | Marburg university

*2020/21*

+ Truth Effect — The role of the response scale in truth effect designs with short delay | Bachelor thesis | Marburg university
